export const quizGenerator = new Map([
    [1, "La regina Elisabetta di inghilterra ha 12 anni"],
    [2, "Il film nella quale affondò una famosa nave è chiamato 'Titanic'"],
    [3, "Gli anni di un cane sono uguali a quelli di un umano"],
    [4, "Le papere possono starnutire"],
    [5, "Gli alligatori sono uccelli con le pinna corte"], 
    [6, "Gli alligatori sono pesci"],
    [7, "La regina Elisabetta ha 20 figli"],
    [8, "Gli alieni hanno inventato la pasta con il tonno"],
    [9, "La codifica UTF-8 in informatica indica una codifica binaria"],
    [10, "Python non è un serpente ma un linguaggio di programmazione"], 
    [11, "Con Javascript è possibile creare una torta e poi mangiarla"],
    [12, "Le macchina furono inventate a seguito dello stancarsi di andare in bici"],
    [13, "Peppa Pig è un cartone animato"],
    [14, "La pantera rosa è un cartone animato"],
    [15, "La televisione è sempre di 26 pollici"],
    [16, "Gabriele D'Annunzio fu uno scienziato nato nel 2010"],
    [17, "Gabriele D'Annunzio fu un poeta"],
    [18, "Gabriele D'Annunzio è un architetto"],
    [19, "Chiara Ferragni sponsorizza bastoncini findus"],
    [20, "Chiara Ferragni pubblicizza molte aziende che producono olive"],
    [21, "Il bodybulding è uno sport"],
    [22, "La regina Elisabetta di inghilterra ha 12 anni"],
    [23, "Nuotare nuoce alla salute se lo si fa circondati da squali"],
    [24, "Il meccanico si occupa di riparare parti della macchina non funzionanti"],
    [25, "Instagram è un social media"],
    [26, "Instagram è un centro di previsioni meteo"],
    [27, "I rinoceronti erano capaci di cucinare"],
    [28, "Gli alieni esistono ma stanno giocando a nascondino"],
    [29, "Gli alieni potrebbero esistere come non potrebbero esistere"],
    [30, "Possiamo fare a meno dell'acqua per cucinare la pasta"],
    [31, "Possiamo fare a meno del sole per cucinare le lenticchie"],
    [32, "La scuola ci prepara a combattere guerre contro le mucche"],
    [33, "La scuola italiana ha come compito quello di garantirci una valida istruzione"],
    [34, "Il creatore di questo sito è brutto"],
    [35, "Il creatore di questo sito è bello"],
    [36, "Il creatore di questo sito si chiama Gianluca"],
    [37, "Il creatore di questo sito si chiama Vincenzo"],
    [38, "Il creatore di questo sito si chiama Giovanno"],
    [39, "Il tuo successo è dato dalla tua determinazione"],
    [40, "Instagram è un centro di previsioni meteo"],
    [41, "La patente di categoria B1 permette di guidare autocarri"],
    [42, "La pasta veniva usata come sacrificio da dare ai grandi Re egiziani"],
    [43, "Gli elefanti sono piccoli e colorati di rosa"],
    [44, "Gli elefanti sono grandi animali"],
    [45, "Le giraffe sono a conoscenza di 4 lingue tra cui l'italiano"],
    [46, "Un prigioniero può evadere dal carcere se lo chiede gentilmente"],
    [47, "Le pizza è buonissima"],
    [48, "Le mucche sono erbivore"],
    [49, "L'america è stata scoperta da Marco Polo"],
    [50, "La gioconda è italiana"],
    [51, "Gli inglesi di solito bevono del tè alle 5 del pomeriggio"],
    [52, "Chissà se questa frase è vera o falsa :)"],
    [53, "Chissà se questa frase è vera o falsa ;)"],
    [54, "Se vediamo un nostro amico in difficoltà dobbiamo prestargli aiuto"],
    [55, "Mai lasciare i propri bro per della pussy :)"],
    [56, "12171 Johannink è un Pianeta"],
    [57, "La Pala di Santa Cristina al Tiverone è un affresco"],
    [58, "Limestone è un comune degli Stati Uniti d'America"],
    [59, "Titabor Town è una suddivisione della Thailandia"],
    [60, "La Charentonne è un lago francese"],
    [61, "La placoglobina è una proteina citoplasmatica"],
    [62, "La donna di picche è una miniserie televisiva italiana"],
    [63, "Padrenda è un comune spagnolo"],
    [64, "Il Contea di Sclafani novello è armonico ed equilibrato"],
    [65, "L'Aeroporto Internazionale di San Antonio è un aeroporto"],
    [66, "Borgotondo è un parco giochi"],
    [67, "Chésalles è una frazione del comune svizzero di Marly"],
    [68, "Steven Irwin era un calciatore del Liverpool"],
    [69, "Ægir è un gigante"],
    [70, "Vero"],
    [71, "Un'immagine è una rappresentazione visiva della realtà"],
    [72, "Il clock è esterno alla CPU"],
    [73, "Un'immagine è una rappresentazione visiva della realtà"],
])

export const quizChecker = new Map([
    [1, false],
    [2, true],
    [3, false],
    [4, true],
    [5, false],
    [6, false],
    [7, false],
    [8, false],
    [9, true],
    [10, true],
    [11, false],
    [12, false],
    [13, true],
    [14, true],
    [15, false],
    [16, false],
    [17, true],
    [18, false],
    [19, false],
    [20, false],
    [21, false],
    [22, true],
    [23, true],
    [24, true],
    [25, true],
    [26, false],
    [27, false],
    [28, false],
    [29, true],
    [30, true],
    [31, true],
    [32, false],
    [33, true],
    [34, false],
    [35, true],
    [36, false],
    [37, true],
    [38, false],
    [39, true],
    [40, false],
    [41, true],
    [42, false],
    [43, true],
    [44, true],
    [45, false],
    [46, false],
    [47, true],
    [48, true],
    [49, true],
    [50, true],
    [51, true],
    [52, false],
    [53, true],
    [54, true],
    [55, true],
    [56, false],
    [57, false],
    [58, true],
    [59, false],
    [60, false],
    [61, true],
    [62, true],
    [63, true],
    [64, true],
    [65, true],
    [66, true],
    [67, true],
    [68, true],
    [69, true],
    [70, true],
    [71, true],
    [72, true],
    [73, true],
])

export const array = [];

export function pushRequest(item) {
    array.push(item)
}

export function clearRequestArray() {
    while(array.length > 0) {
        array.pop();
    }
}

export function randomNumber(max) {
    return Math.floor(Math.random() * (max + 1));
}

export function checkRequest(request) {
    for(let i = 0; i < array.length; i++) {
        if(request == array[i])
            return 0;
    }
    return 1;
}